language: node_js
node_js:
  - "4.2"
sudo: false

script:
  - ./node_modules/.bin/gulp eslint
  - ./node_modules/.bin/gulp unit

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

deploy:
  provider: script
  script: "./node_modules/.bin/gulp deploy"
  on:
    branch: master